public class FrameworkConstants {
    public static final String APPLICATION_STATUS_IN_PROGRESS = 'InProgress';
    public static final String APPLICATION_STATUS_COMPLETED = 'Completed';
    public static final String CONVERSION_STATUS_NOT_READY = 'NotReady';
    public static final String EVENT_APPLICATION_INITIALIZED = 'ApplicationInitialized';
    public static final String EVENT_APPLICATION_FINISHED = 'ApplicationFinished';
    public static final String EVENT_SNAPSHOT_RETURNED = 'SnapshotReturned';
    public static final String EVENT_STEP_SUBMITTED = 'StepSubmitted';
}
