public class FrameworkConstants {
    public static final String APPLICATION_STATUS_IN_PROGRESS = 'InProgress';
    public static final String APPLICATION_STATUS_COMPLETED = 'Completed';
    public static final String CONVERSION_STATUS_NOT_READY = 'NotReady';
    public static final String EVENT_APPLICATION_INITIALIZED = 'ApplicationInitialized';
    public static final String EVENT_APPLICATION_FINISHED = 'ApplicationFinished';
    public static final String EVENT_JOB_QUEUED = 'JobQueued';
    public static final String EVENT_JOB_STARTED = 'JobStarted';
    public static final String EVENT_JOB_COMPLETED = 'JobCompleted';
    public static final String EVENT_JOB_FAILED = 'JobFailed';
    public static final String EVENT_SNAPSHOT_RETURNED = 'SnapshotReturned';
    public static final String EVENT_STEP_SUBMITTED = 'StepSubmitted';
    public static final String EVENT_STOP_PROCESS_ACTIVATED = 'StopProcessActivated';
    public static final String EVENT_TRANSITION_BLOCKED = 'TransitionBlocked';
    public static final String EVENT_TRANSITION_COMPLETED = 'TransitionCompleted';
    public static final String JOB_STATUS_QUEUED = 'Queued';
    public static final String JOB_STATUS_PREPARING = 'Preparing';
    public static final String JOB_STATUS_PROCESSING = 'Processing';
    public static final String JOB_STATUS_COMPLETED = 'Completed';
    public static final String JOB_STATUS_FAILED = 'Failed';
    public static final String JOB_STATUS_RESTART = 'Restart';
    public static final String JOB_EXECUTION_MODE_SYNC = 'sync';
    public static final String STOP_PROCESS_STATUS_ACTIVE = 'Active';
    public static final String STOP_PROCESS_STATUS_RESOLVED = 'Resolved';
}
