public class FrameworkErrorCodes {
    public static final String ACCESS_DENIED = 'ACCESS_DENIED';
    public static final String APPLICATION_NOT_FOUND = 'APPLICATION_NOT_FOUND';
    public static final String BLOCKED_BY_RULE = 'BLOCKED_BY_RULE';
    public static final String CONVERSION_ERROR = 'CONVERSION_ERROR';
    public static final String DEFINITION_ERROR = 'DEFINITION_ERROR';
    public static final String INTEGRATION_ERROR = 'INTEGRATION_ERROR';
    public static final String INVALID_APPLICATION_STATE = 'INVALID_APPLICATION_STATE';
    public static final String INVALID_REQUEST = 'INVALID_REQUEST';
    public static final String JOB_NOT_FOUND = 'JOB_NOT_FOUND';
    public static final String JOB_NOT_RUNNABLE = 'JOB_NOT_RUNNABLE';
    public static final String MAPPING_ERROR = 'MAPPING_ERROR';
    public static final String RULE_ERROR = 'RULE_ERROR';
    public static final String UNKNOWN_ERROR = 'UNKNOWN_ERROR';
}
